name: BSKits
version: '1.0-SNAPSHOT'
main: org.ozaii.bskits.BSKits
api-version: '1.19'
authors: [ozaii]
description: Minecraft sunucunuz için gelişmiş kit sistemi
commands:
  kit:
    description: Kit yönetim komutları
    tab-completer: org.ozaii.bskits.command.KitCommandTabCompleter
    aliases: [kits]
    permissions:
      kit.use:
        description: "Kit komutlarını kullanma izni"
        default: op